import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col justify-center bg-black text-white">
        <header className="flex flex-row m-auto w-full">
          <div className="w-1/2 p-5 pl-80">
            <Link key="" href='/' className="hover:text-accent font-extrabold text-lg">
              Digital success take home assignment
            </Link>
          </div>
          <div className="w-1/2 p-5 pl-60 flex flex-row font-extrabold text-lg">
            <div>By</div>
            <Image
                    src="/vercel.svg"
                    alt="Vercel logomark"
                    width={20}
                    height={20}
                  />
            <div>Vercel</div>
        </div>
        </header>
        {children}
        </div>
      </body>
    </html>
  );
}
